[package]
name = "actix-ecommerce"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
auth = {git="https://github.com/Ferrumec/auth"}
catalog = {git="https://github.com/Ferrumec/catalog"}
orders = {git="https://github.com/Austin-rgb/orders"}
inventory = {git="https://github.com/Ferrumec/inventory"}
tenant ={git="https://github.com/Austin-rgb/tenant"}
dotenvy = "0.15.7"
ferrumec={git="https://github.com/Austin-rgb/ferrumec"}
cart = {git="https://github.com/Austin-rgb/cart"}
futures = "0.3.32"
notification = {git="https://github.com/Ferrumec/notification"}
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing = "0.1.44"
sqlx = { version = "0.8.6", features = ["sqlite"] }
actixutils = { path = "../actixutils" }
event-stream = { path = "../event-stream" }
emailgrid = {path="../emailgrid"}
# --- Local overrides ---

[patch."https://github.com/Ferrumec/auth"]
auth = { path = "../auth" }

[patch."https://github.com/Ferrumec/catalog"]
catalog = { path = "../catalog" }

[patch."https://github.com/Austin-rgb/orders"]
orders = { path = "../orders" }

[patch."https://github.com/Ferrumec/inventory"]
inventory = { path = "../inventory" }

[patch."https://github.com/Austin-rgb/tenant"]
tenant = { path = "../tenant" }

[patch."https://github.com/Austin-rgb/cart"]
cart = { path = "../cart" }

[patch."https://github.com/Austin-rgb/ferrumec"]
ferrumec = { path = "../ferrumec" }

[patch."https://github.com/Ferrumec/notification"]
notification = { path = "../notification" }

