services:
  - type: web
    name: actix-api
    runtime: image
    image:
      url: ghcr.io/austin-rgb/actix-ecommerce:latest
    envVars:
      - key: NATS_URL
        value: nats://nats:4222
      - key: DATABASE_URL
        value: sqlite:/var/data/database.db

  - type: web
    name: nats
    runtime: image
    image:
      url: nats:2.10-alpine
